//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBH_App.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToan
    {
        public int Id { get; set; }
        public string MaKH { get; set; }
        public Nullable<decimal> SoTienDaTra { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
